schema_version = 3

[[cases]]
id = "module_1_bandgap_reference.part_3_layout.OTA_layout.full_OTA"
config_path = "cases/full_OTA/case.toml"

[[cases]]
id = "module_1_bandgap_reference.part_3_layout.OTA_layout.input_pair"
config_path = "cases/input_pair/case.toml"

[[cases]]
id = "module_1_bandgap_reference.part_3_layout.OTA_layout.output_stage"
config_path = "cases/output_stage/case.toml"

[[cases]]
id = "module_3_8_bit_SAR_ADC.part_5_analog_layout.comparator"
config_path = "cases/comparator/case.toml"
