schema_version = 3

[[cases]]
id = "ihp-sg13g2.analog-db.amp_001_5t"
config_path = "cases/amp_001_5t/case.toml"

[[cases]]
id = "ihp-sg13g2.analog-db.sw_002_chopper_diff"
config_path = "cases/sw_002_chopper_diff/case.toml"

[[cases]]
id = "ihp-sg13g2.analog-db.buf_001_super_follower"
config_path = "cases/buf_001_super_follower/case.toml"

[[cases]]
id = "ihp-sg13g2.analog-db.cmfb_004_output_switched_cap"
config_path = "cases/cmfb_004_output_switched_cap/case.toml"

[[cases]]
id = "ihp-sg13g2.analog-db.sw_003_binary_capbank"
config_path = "cases/sw_003_binary_capbank/case.toml"

[[cases]]
id = "ihp-sg13g2.analog-db.amp_024_smcnr"
config_path = "cases/amp_024_smcnr/case.toml"

[[cases]]
id = "ihp-sg13g2.analog-db.amp_023_fer_fd2s"
config_path = "cases/amp_023_fer_fd2s/case.toml"

[[cases]]
id = "ihp-sg13g2.analog-db.ia_006_fan_chopper_cmfb"
config_path = "cases/ia_006_fan_chopper_cmfb/case.toml"

[[cases]]
id = "ihp-sg13g2.analog-db.smp_001_nmos_th"
config_path = "cases/smp_001_nmos_th/case.toml"

[[cases]]
id = "ihp-sg13g2.analog-db.amp_008_leung_nmcf"
config_path = "cases/amp_008_leung_nmcf/case.toml"

[[cases]]
id = "ihp-sg13g2.analog-db.amp_009_leung_nmcnr"
config_path = "cases/amp_009_leung_nmcnr/case.toml"

[[cases]]
id = "ihp-sg13g2.analog-db.amp_002_alfio_raffc"
config_path = "cases/amp_002_alfio_raffc/case.toml"

[[cases]]
id = "ihp-sg13g2.analog-db.amp_003_fan_smc"
config_path = "cases/amp_003_fan_smc/case.toml"

[[cases]]
id = "ihp-sg13g2.analog-db.ldo_009_fer_5t_pass"
config_path = "cases/ldo_009_fer_5t_pass/case.toml"

[[cases]]
id = "ihp-sg13g2.analog-db.amp_005_hoilee_affc"
config_path = "cases/amp_005_hoilee_affc/case.toml"

[[cases]]
id = "ihp-sg13g2.analog-db.amp_010_peng_acbc"
config_path = "cases/amp_010_peng_acbc/case.toml"

[[cases]]
id = "ihp-sg13g2.analog-db.trm_001_vcr"
config_path = "cases/trm_001_vcr/case.toml"

[[cases]]
id = "ihp-sg13g2.analog-db.amp_007_leung_dfcfc2"
config_path = "cases/amp_007_leung_dfcfc2/case.toml"

[[cases]]
id = "ihp-sg13g2.analog-db.ldo_008_fer_mirror_ota"
config_path = "cases/ldo_008_fer_mirror_ota/case.toml"

[[cases]]
id = "ihp-sg13g2.analog-db.amp_006_leung_dfcfc1"
config_path = "cases/amp_006_leung_dfcfc1/case.toml"

[[cases]]
id = "ihp-sg13g2.analog-db.amp_012_peng_tcfc"
config_path = "cases/amp_012_peng_tcfc/case.toml"

[[cases]]
id = "ihp-sg13g2.analog-db.amp_015_sau_cfcc"
config_path = "cases/amp_015_sau_cfcc/case.toml"

[[cases]]
id = "ihp-sg13g2.analog-db.ldo_001_analoggym_basic"
config_path = "cases/ldo_001_analoggym_basic/case.toml"

[[cases]]
id = "ihp-sg13g2.analog-db.vref_001_vgs"
config_path = "cases/vref_001_vgs/case.toml"



[[cases]]
id = "ihp-sg13g2.analog-db.drv_001_pam4_sige_dac"
config_path = "cases/drv_001_pam4_sige_dac/case.toml"

[[cases]]
id = "ihp-sg13g2.analog-db.amp_027_fan_rrl_ota"
config_path = "cases/amp_027_fan_rrl_ota/case.toml"

[[cases]]
id = "ihp-sg13g2.analog-db.amp_026_fan_chopper_ota"
config_path = "cases/amp_026_fan_chopper_ota/case.toml"

[[cases]]
id = "ihp-sg13g2.analog-db.ia_002_fan_chopper_simple"
config_path = "cases/ia_002_fan_chopper_simple/case.toml"

[[cases]]
id = "ihp-sg13g2.analog-db.ia_003_fan_chopper_pf"
config_path = "cases/ia_003_fan_chopper_pf/case.toml"

[[cases]]
id = "ihp-sg13g2.analog-db.amp_014_ramos_pfc"
config_path = "cases/amp_014_ramos_pfc/case.toml"

[[cases]]
id = "ihp-sg13g2.analog-db.amp_011_peng_iac"
config_path = "cases/amp_011_peng_iac/case.toml"

[[cases]]
id = "ihp-sg13g2.analog-db.amp_016_song_dacfc"
config_path = "cases/amp_016_song_dacfc/case.toml"

[[cases]]
id = "ihp-sg13g2.analog-db.amp_013_qu2017_azc"
config_path = "cases/amp_013_qu2017_azc/case.toml"

[[cases]]
id = "ihp-sg13g2.analog-db.amp_021_yan_az"
config_path = "cases/amp_021_yan_az/case.toml"

[[cases]]
id = "ihp-sg13g2.analog-db.amp_034_fan_chopper_cmfb"
config_path = "cases/amp_034_fan_chopper_cmfb/case.toml"

[[cases]]
id = "ihp-sg13g2.analog-db.amp_035_fan_chopper_cmfb_dual"
config_path = "cases/amp_035_fan_chopper_cmfb_dual/case.toml"

[[cases]]
id = "ihp-sg13g2.analog-db.amp_022_fer_two_stage"
config_path = "cases/amp_022_fer_two_stage/case.toml"

[[cases]]
id = "ihp-sg13g2.analog-db.amp_029_two_stage_miller_comp"
config_path = "cases/amp_029_two_stage_miller_comp/case.toml"

[[cases]]
id = "ihp-sg13g2.analog-db.cmfb_002_5t_pmos_input"
config_path = "cases/cmfb_002_5t_pmos_input/case.toml"

[[cases]]
id = "ihp-sg13g2.analog-db.sw_001_transmission_gate_pair"
config_path = "cases/sw_001_transmission_gate_pair/case.toml"

[[cases]]
id = "ihp-sg13g2.analog-db.adc_001_inv1b"
config_path = "cases/adc_001_inv1b/case.toml"
