schema_version = 3

[[cases]]
id = "freepdk45.OpenRAM.cell_6t"
config_path = "cases/cell_6t/case.toml"

[[cases]]
id = "freepdk45.OpenRAM.sense_amp"
config_path = "cases/sense_amp/case.toml"

[[cases]]
id = "freepdk45.OpenRAM.write_driver"
config_path = "cases/write_driver/case.toml"
