schema_version = 3

[[cases]]
id = "freepdk45.nangate45-pdk.NAND2_X1"
config_path = "cases/NAND2_X1/case.toml"

[[cases]]
id = "freepdk45.nangate45-pdk.AOI21_X1"
config_path = "cases/AOI21_X1/case.toml"
